# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize:
          gcloud-service-key: GCLOUD_SERVICE_KEY
          google-compute-region: AUSTRALIA_REGION
          #google-compute-zone: <<parameters.google-compute-zone>>
          google-project-id: GOOGLE_PROJECT_ID

      - run: |
          echo hello
          gcloud projects list

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      

