name: dev-static-website

on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    name: Deploy to Development
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.MYKEY }}
        aws-secret-access-key: ${{ secrets.MYSECRET }}
        aws-region: ap-southeast-2
          
    - name: Build and Test.
      run: |
        npm install
        npm run test
        npm run build

    - name: Copy to dev.craiggunson.com bucket.
      run: |
        cd build
        aws s3 sync . s3://dev.craiggunson.com --acl public-read --cache-control "max-age=60"  --delete \
        --exclude '.git*' \
        --exclude '.github*'
        

