name: token

on:
  push:
    branches:
      - 'retry-check2'
      
permissions:
  actions: write
  contents: read

jobs:
  token:
    name: token
    if: ${{ github.run_attempt <= 2 }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

      
    - name: token
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        output=$(gh run view --repo "${{ github.event.repository.full_name }}" "${{ github.run_id }}")
        echo "$output"
        gh workflow run dispatch.yml
          --repo "${{ github.event.repository.full_name }}" \
          --ref "${{ github.ref_name }}"

